/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TurnTablePosition } from "./TurnTablePosition";
import { TurnTablePositionCountArgs } from "./TurnTablePositionCountArgs";
import { TurnTablePositionFindManyArgs } from "./TurnTablePositionFindManyArgs";
import { TurnTablePositionFindUniqueArgs } from "./TurnTablePositionFindUniqueArgs";
import { DeleteTurnTablePositionArgs } from "./DeleteTurnTablePositionArgs";
import { TurnTablePositionService } from "../turnTablePosition.service";
@graphql.Resolver(() => TurnTablePosition)
export class TurnTablePositionResolverBase {
  constructor(protected readonly service: TurnTablePositionService) {}

  async _turnTablePositionsMeta(
    @graphql.Args() args: TurnTablePositionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TurnTablePosition])
  async turnTablePositions(
    @graphql.Args() args: TurnTablePositionFindManyArgs
  ): Promise<TurnTablePosition[]> {
    return this.service.turnTablePositions(args);
  }

  @graphql.Query(() => TurnTablePosition, { nullable: true })
  async turnTablePosition(
    @graphql.Args() args: TurnTablePositionFindUniqueArgs
  ): Promise<TurnTablePosition | null> {
    const result = await this.service.turnTablePosition(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TurnTablePosition)
  async deleteTurnTablePosition(
    @graphql.Args() args: DeleteTurnTablePositionArgs
  ): Promise<TurnTablePosition | null> {
    try {
      return await this.service.deleteTurnTablePosition(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
