/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CentroidData } from "./CentroidData";
import { CentroidDataCountArgs } from "./CentroidDataCountArgs";
import { CentroidDataFindManyArgs } from "./CentroidDataFindManyArgs";
import { CentroidDataFindUniqueArgs } from "./CentroidDataFindUniqueArgs";
import { DeleteCentroidDataArgs } from "./DeleteCentroidDataArgs";
import { CentroidDataService } from "../centroidData.service";
@graphql.Resolver(() => CentroidData)
export class CentroidDataResolverBase {
  constructor(protected readonly service: CentroidDataService) {}

  async _centroidDataItemsMeta(
    @graphql.Args() args: CentroidDataCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CentroidData])
  async centroidDataItems(
    @graphql.Args() args: CentroidDataFindManyArgs
  ): Promise<CentroidData[]> {
    return this.service.centroidDataItems(args);
  }

  @graphql.Query(() => CentroidData, { nullable: true })
  async centroidData(
    @graphql.Args() args: CentroidDataFindUniqueArgs
  ): Promise<CentroidData | null> {
    const result = await this.service.centroidData(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CentroidData)
  async deleteCentroidData(
    @graphql.Args() args: DeleteCentroidDataArgs
  ): Promise<CentroidData | null> {
    try {
      return await this.service.deleteCentroidData(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
