/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { OutputFilename } from "./OutputFilename";
import { OutputFilenameCountArgs } from "./OutputFilenameCountArgs";
import { OutputFilenameFindManyArgs } from "./OutputFilenameFindManyArgs";
import { OutputFilenameFindUniqueArgs } from "./OutputFilenameFindUniqueArgs";
import { DeleteOutputFilenameArgs } from "./DeleteOutputFilenameArgs";
import { OutputFilenameService } from "../outputFilename.service";
@graphql.Resolver(() => OutputFilename)
export class OutputFilenameResolverBase {
  constructor(protected readonly service: OutputFilenameService) {}

  async _outputFilenamesMeta(
    @graphql.Args() args: OutputFilenameCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [OutputFilename])
  async outputFilenames(
    @graphql.Args() args: OutputFilenameFindManyArgs
  ): Promise<OutputFilename[]> {
    return this.service.outputFilenames(args);
  }

  @graphql.Query(() => OutputFilename, { nullable: true })
  async outputFilename(
    @graphql.Args() args: OutputFilenameFindUniqueArgs
  ): Promise<OutputFilename | null> {
    const result = await this.service.outputFilename(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OutputFilename)
  async deleteOutputFilename(
    @graphql.Args() args: DeleteOutputFilenameArgs
  ): Promise<OutputFilename | null> {
    try {
      return await this.service.deleteOutputFilename(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
